// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/products": {
            "get": {
                "description": "List all products with optional category filtering",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "List products",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by category ID",
                        "name": "category_id",
                        "in": "query"
                    },
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "default": 50,
                        "description": "Limit size",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "minimum": 0,
                        "type": "integer",
                        "default": 0,
                        "description": "Offset",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/backend_internal_domain.ListResponse-backend_internal_domain_ProductDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/backend_internal_response.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/backend_internal_response.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/backend_internal_response.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "backend_internal_domain.CategoryDTO": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "isActive": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "backend_internal_domain.ListResponse-backend_internal_domain_ProductDTO": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/backend_internal_domain.ProductDTO"
                    }
                }
            }
        },
        "backend_internal_domain.MenuDTO": {
            "type": "object",
            "properties": {
                "slots": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/backend_internal_domain.MenuSlotDTO"
                    }
                }
            }
        },
        "backend_internal_domain.MenuSlotDTO": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "menuSlotItems": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/backend_internal_domain.MenuSlotItemDTO"
                    }
                },
                "name": {
                    "type": "string"
                },
                "sequence": {
                    "type": "integer"
                }
            }
        },
        "backend_internal_domain.MenuSlotItemDTO": {
            "type": "object",
            "properties": {
                "category": {
                    "$ref": "#/definitions/backend_internal_domain.CategoryDTO"
                },
                "id": {
                    "type": "string"
                },
                "image": {
                    "type": "string"
                },
                "isActive": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "priceCents": {
                    "type": "integer"
                },
                "type": {
                    "$ref": "#/definitions/backend_internal_domain.ProductType"
                }
            }
        },
        "backend_internal_domain.ProductDTO": {
            "type": "object",
            "properties": {
                "category": {
                    "$ref": "#/definitions/backend_internal_domain.CategoryDTO"
                },
                "id": {
                    "type": "string"
                },
                "image": {
                    "type": "string"
                },
                "isActive": {
                    "type": "boolean"
                },
                "menu": {
                    "$ref": "#/definitions/backend_internal_domain.MenuDTO"
                },
                "name": {
                    "type": "string"
                },
                "priceCents": {
                    "type": "integer"
                },
                "type": {
                    "$ref": "#/definitions/backend_internal_domain.ProductType"
                }
            }
        },
        "backend_internal_domain.ProductType": {
            "type": "string",
            "enum": [
                "simple",
                "menu"
            ],
            "x-enum-varnames": [
                "ProductTypeSimple",
                "ProductTypeMenu"
            ]
        },
        "backend_internal_response.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "boolean"
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{"http", "https"},
	Title:            "Bless2n Food System API",
	Description:      "Internal BlessThun Food System API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
