name: Generate Backend Code
description: Run Ent and OpenAPI code generation for the Go backend

runs:
  using: composite
  steps:
    - name: Generate Ent
      shell: bash
      working-directory: bfs-backend
      run: |
        mkdir -p ./internal/generated/ent
        echo "package ent" > ./internal/generated/ent/ent.go
        go run -mod=mod entgo.io/ent/cmd/ent generate --feature sql/modifier --feature sql/upsert --target ./internal/generated/ent ./internal/schema

    - name: Generate OpenAPI
      shell: bash
      working-directory: bfs-backend
      run: |
        npx @redocly/cli bundle openapi/openapi.yaml -o openapi/bundled.yaml
        go install github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen@v2.5.1
        oapi-codegen -config oapi-codegen.yaml openapi/bundled.yaml
