CREATE TABLE event_device (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id nano_id NOT NULL,
    device_id nano_id NOT NULL,
    assigned_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    FOREIGN KEY (event_id) REFERENCES event (id) ON DELETE CASCADE,
    FOREIGN KEY (device_id) REFERENCES device (id) ON DELETE CASCADE
);