ALTER TABLE role ENABLE ROW LEVEL SECURITY;
ALTER TABLE user ENABLE ROW LEVEL SECURITY;
ALTER TABLE verification_token ENABLE ROW LEVEL SECURITY;
ALTER TABLE password_reset_token ENABLE ROW LEVEL SECURITY;
ALTER TABLE refresh_token ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE event ENABLE ROW LEVEL SECURITY;
ALTER TABLE event_role ENABLE ROW LEVEL SECURITY;
ALTER TABLE event_user ENABLE ROW LEVEL SECURITY;
ALTER TABLE event_invite ENABLE ROW LEVEL SECURITY;
ALTER TABLE device ENABLE ROW LEVEL SECURITY;
ALTER TABLE event_device ENABLE ROW LEVEL SECURITY;
ALTER TABLE device_pairing ENABLE ROW LEVEL SECURITY;
ALTER TABLE event_category ENABLE ROW LEVEL SECURITY;
ALTER TABLE event_product ENABLE ROW LEVEL SECURITY;
ALTER TABLE customer_order ENABLE ROW LEVEL SECURITY;
ALTER TABLE customer_order_item ENABLE ROW LEVEL SECURITY;

